config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :categories
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
require 'date'
class Article < ApplicationRecord
	mount_uploader :feature_image_url, CoverUploader

	belongs_to :category

	validates_presence_of :title, :body, :category_id, :publish_date, :feature_image_url
	validate :publish_date_cannot_be_more_than_one_month_from_today, on: [:create, :update]
	validate :publish_date_in_the_past, on: [:create, :update]
	validate :publish_date_in_the_future, on: [:create, :update]

	def publish_date_cannot_be_more_than_one_month_from_today
		if publish_date > Date.today.next_month
			errors.add(:publish_date, "can't be greater than one month from today")
		end
	end

	def publish_date_in_the_past
		if publish_date <= Date.today
			is_published = true
		end
	end

	def publish_date_in_the_future
		if publish_date > Date.today
			is_published = false
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles

	validates_presence_of :name, :description
	validates_uniqueness_of :name
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(params[:article].permit(:title, :body, :category_id, :publish_date, :feature_image_url, :is_published))
		if @article.save
			redirect_to article_path(@article.id), notice: "Article successfully created!"
		else
			render action: 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(params[:article].permit(:title, :body, :category_id, :publish_date, :feature_image_url, :is_published))
			redirect_to article_path(@article.id), notice: "Article successfully updated!"
		else
			render action: 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path, notice: "Article successfully deleted!"
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def show
		@category = Category.find(params[:id])
	end

	def edit
		@category = Category.find(params[:id])
	end

	def create
		@category = Category.new(params[:category].permit(:name, :description))
		if @category.save
			redirect_to categories_path, notice: "Category added successfully!"
		else
			render action: 'new'
		end
	end

	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(params[:category].permit(:name, :description))
			redirect_to categories_path, notice: "Category updated successfully!"
		else
			render action: 'edit'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path, notice: "Category deleted successfully!"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

<% if @article.errors.any? %>
	<h3>Your article could not be saved because:</h3>
	<ol>
		<% @article.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %><br/>
			</li>
		<% end %>
	</ol>
<% end %>

<label for="article_category_id">Category: </label><br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %> <br/>

<label for="article_title">Title:</label><br/>
<%= f.text_field :title, placeholder: "Enter article title" %><br/>

<label for="article_body">Body:</label><br/>
<%= f.cktext_area :body, placeholder: "Enter your article in this space." %><br/>

<label for="publish_date">Published On:</label><br/>
<%= f.text_field :publish_date %><br/>

<%= f.label :feature_image_url %>
<%= f.file_field :feature_image_url %>


<%= f.submit %><br/>

<% end %>

app/views/articles/edit.html.erb
<h2>Edit Article(<%= @article.title %>)</h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="row">

	<!-- Blog Entries Column -->
	<div class="col-md-8">

	  <h1 class="my-4">All Articles
	    <small><%= @articles.length %></small>
	  </h1>

	  <!-- Blog Post -->
	  <% @articles.each do |article| %>
	  <div class="card mb-4">
	  <%= image_tag(article.feature_image_url, size: "750x300", class: "card-img-top") %>
	    <div class="card-body">
	      <h2 class="card-title"><%= article.title %></h2>
	      <p class="card-text"><%= article.body.truncate(200) %></p>
	      <%= link_to "Read More", article, class: "btn btn-primary" %>
	    </div>
	    <div class="card-footer text-muted">
	      Posted on <%= article.publish_date.strftime("%B %d %Y") %>
	      <%= link_to article.category.name, article.category %>
	    </div>
	  </div>
	  <% end %>

	  <%= render '/categories/list' %>
</div>

app/views/articles/new.html.erb
<h2>Add Article</h2>
<%= render 'form' %>

app/views/articles/show.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h1 class="mt-4"><%= @article.title %></h1>

      <!-- Author -->
      <p class="lead">
        in
        <%= link_to @article.category.name, @article.category %>
      </p>

      <hr>

      <!-- Date/Time -->
      <p>Posted on <%= @article.publish_date.strftime("%B %d %Y %H:%M %p") %></p>

      <hr>

      <!-- Preview Image -->
      <%= image_tag(@article.feature_image_url, size: "900x300", class: "img-fluid rounded") %>

      <hr>

      <!-- Post Content -->
      <p><%= raw(@article.body) %></p>

      <hr>

      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
          <form>
            <div class="form-group">
              <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>

      <!-- Single Comment -->
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0"></h5>
          Very Nice article. Quite informative.
        </div>
      </div>

    <%= render '/categories/list' %>
   </div>
  </div>
</div>
<!-- /.container -->

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
	
	<% if @category.errors.any? %>
	<h3>Your category could not be added because:</h3>
		<ul>
			<% @category.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %><br/>
				</li>
			<% end %>
		</ul>
	<% end %>

	<label for="category_name">Name:</label><br/>
	<%= f.text_field :name, placeholder: "Enter category name" %><br/>

	<label for="category_description">Description:</label><br/>
	<%= f.text_area :description, min: 10, placeholder: "Enter description of minimum 10 words" %><br/>

	<%= f.submit %><br/>

<% end %>
		

app/views/categories/_list.html.erb
<!-- Pagination -->
  <ul class="pagination justify-content-center mb-4">
    <li class="page-item">
      <a class="page-link" href="#">&larr; Older</a>
    </li>
    <li class="page-item disabled">
      <a class="page-link" href="#">Newer &rarr;</a>
    </li>
  </ul>

</div>

<!-- Sidebar Widgets Column -->
<div class="col-md-4">

  <!-- Search Widget -->
  <div class="card my-4">
    <h5 class="card-header">Search</h5>
    <div class="card-body">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="button">Go!</button>
        </span>
      </div>
    </div>
  </div>

  <!-- Categories Widget -->
  <div class="card my-4">
    <h5 class="card-header">Categories</h5>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6">
          <ul class="list-unstyled mb-0">
            <li>
              <a href="#">Web Design</a>
            </li>
            <li>
              <a href="#">HTML</a>
            </li>
            <li>
              <a href="#">Freebies</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-6">
          <ul class="list-unstyled mb-0">
            <li>
              <a href="#">JavaScript</a>
            </li>
            <li>
              <a href="#">CSS</a>
            </li>
            <li>
              <a href="#">Tutorials</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Side Widget -->
  <div class="card my-4">
    <h5 class="card-header">Side Widget</h5>
    <div class="card-body">
      You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
    </div>
  </div>

</div>

app/views/categories/edit.html.erb
<h2>Edit Category(<%= @category.name %>)</h2>
<%= render 'form' %>

app/views/categories/index.html.erb
<div class="row">

	<!-- Blog Entries Column -->
	<div class="col-md-8">

	  <h1 class="my-4">All Categories
	    <small><%= @categories.length %></small>
	  </h1>

	  <!-- Blog Post -->
	<% if @categories.empty? %>
	  <p>No categories found.</p>
	<% else %>
	  <% @categories.each do |category| %>
	  <div class="card mb-4">
	    <div class="card-body">
	    		<h2 class="card-title"><%= link_to category.name, category_path(category.id) %>(<%= Article.where('category_id=?', category.id).length %>)</h2>
	    		<p class="card-text"><%= category.description %></p>

	    </div>
	  </div>
	  <% end %>
	<% end %>
	<%= render '/categories/list' %>
</div>

app/views/categories/new.html.erb
<h2>Add Category</h2>
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="row">

	<!-- Blog Entries Column -->
	<div class="col-md-8">

	  <h1 class="my-4">Articles in <%= @category.name %>
	  </h1>

	  <!-- Blog Post -->
	  <% @articles = Article.where('category_id=?',@category.id) %>

	  <% if @articles.empty? %>
		<p>No products found.</p>
	  <% else %>
		  <% @articles.each do |article| %>
		  <div class="card mb-4">
		  <%= image_tag(article.feature_image_url, size: "750x300", class: "card-img-top") %>
		    <div class="card-body">
		    		<h2 class="card-title"><%= article.title %></h2>
		    		<p class="card-text"><%= article.body.truncate(200) %></p>
	      			<%= link_to "Read More", article, class: "btn btn-primary" %>
		    </div>
		    <div class="card-footer text-muted">
		      Posted on <%= article.publish_date.strftime("%B %d %Y") %>
		    </div>
		  </div>
		  <% end %>
	  <% end %>

	  <%= render 'list' %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">My Blog Application</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/articles">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/categories">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <script src="/javascripts/jquery.js"></script>
    <script src="/javascripts/bootstrap.js"></script>

    <link rel="stylesheet" href="/stylesheets/bootstrap.css" />
    <link rel="stylesheet" href="/stylesheets/blog-home.css" />

  </head>

  <body>
  <div class="mb-3"></div>
    <%= render '/layouts/nav' %>
    <div class="container">
    <%= notice %>
    <%= alert %>
    <%= yield %>
    </div>
    <!-- Footer -->
    <div class="mb-5"></div>
    <footer class="py-1 bg-dark fixed-bottom">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; My Blog Application 2018</p>
      </div>
      <!-- /.container -->
    </footer>
  </body>
</html>